### ISSUE TITLE
If you try and combine increment and add-snapshot directly in pom they overwrite each other

### ISSUE THREAD

**Issue by danrussell74** [petr-ujezdsky/versions-maven-plugin#1]
If you try and increment and add snapshot directly from maven then the second change gets overwritten.
```
<plugin>
	<groupId>org.codehaus.mojo</groupId>
	<artifactId>versions-maven-plugin</artifactId>
	<version>2.1-with-increment</version>
	<executions>
		<execution>
			<phase>validate</phase>
			<id>increment-version</id>
			<goals>
				<goal>increment</goal>
			</goals>
		</execution>
		<execution>
			<phase>validate</phase>
			<id>set-to-snapshot</id>
			<goals>
				<goal>add-snapshot</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```
[INFO]     Updating project accounts-rest
[INFO]         from version 0.0.19 to 0.0.20
Props: {project.version=0.0.20, project.parent.version=1.2.1.RELEASE, project.parent.groupId=org.springframework.boot, project.artifactId=accounts-rest, proj
.groupId=XXX, project.parent.artifactId=spring-boot-starter-parent}
[INFO]
[INFO]
[INFO] --- versions-maven-plugin:2.1-with-increment:add-snapshot (set-to-snapshot) @ accounts-rest ---
[INFO] Searching for local aggregator root...
[INFO] Local aggregation root: c:\workspaces\accounts-rest
[INFO] Processing XXX:accounts-rest
[INFO]     Updating project XXX:accounts-rest
[INFO]         from version 0.0.19 to 0.0.19-SNAPSHOT
Props: {project.version=0.0.19-SNAPSHOT, project.parent.version=1.2.1.RELEASE, project.parent.groupId=org.springframework.boot, project.artifactId=accounts-r
, project.groupId=XXX project.parent.artifactId=spring-boot-starter-parent}

**Comment by petr-ujezdsky** [comment]
Thank you for bug report. I knew about this problem and temporarily fixed it by calling whole maven twice.
Now I found some time for real fix, hope it will help :)

**Comment by danrussell74** [comment]
Yes calling maven twice is what i did as well

**Comment by petr-ujezdsky** [comment]
I have fixed that issue in my last commit. I have tested it using your example and it worked.
I have also forked the official repo and created a [pull request] (https://github.com/mojohaus/versions-maven-plugin/pull/23).
